name: Hardcore
version: Beta 1.1
Author: Dianelito
main: hd.dianelito.Hardcore
api-version: 1.13
description: Este plugin agregara sistema de vidas y más para una modalidad hardcore
softdepend:
  - LuckPerms

commands:
  lifes:
    description: ver cuantas vidas tienes
    aliases:
    - vidas
    - vida
    - life
    - live
    - lives